title: √Ålvaro Navarro Rubio Portfolio
description: Data Analyst Portfolio showcasing Excel, SQL, Power BI and Python projects.
baseurl: "" # leave empty for root
url: "https://AlvaroNavR.github.io"
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
